/* Generated By:JavaCC: Do not edit this line. PreProcessorParserConstants.java */
package taems.preprocessor;

public interface PreProcessorParserConstants {

  int EOF = 0;
  int COMMENT = 1;
  int IF = 7;
  int ENDIF = 8;
  int ELSEIF = 9;
  int ELSE = 10;
  int DEFINE = 11;
  int DEFINENOW = 12;
  int ENDDEFINE = 13;
  int WHILE = 14;
  int ENDWHILE = 15;
  int GREATER = 16;
  int LESSER = 17;
  int EQUAL = 18;
  int NOTEQUAL = 19;
  int LPAREN = 20;
  int RPAREN = 21;
  int AND = 22;
  int OR = 23;
  int DOLLAR = 24;
  int AT = 25;
  int RANDOMFLOAT = 26;
  int RANDOMLIST = 27;
  int RANDOMINT = 28;
  int PROD = 29;
  int SUM = 30;
  int DIFF = 31;
  int QUOT = 32;
  int ROUND = 33;
  int TRIM = 34;
  int SPACE = 35;
  int DEF = 36;
  int NDEF = 37;
  int CONCAT = 38;
  int LENGTH = 39;
  int GETITEMAT = 40;
  int ADDITEMAT = 41;
  int DELITEMAT = 42;
  int POUND = 43;
  int AFFECT = 44;
  int COMMA = 45;
  int ID = 46;
  int SPECIAL = 47;
  int NUM = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"#if\"",
    "\"#endif\"",
    "\"#elseif\"",
    "\"#else\"",
    "\"#define\"",
    "\"#definenow\"",
    "\"#enddefine\"",
    "\"#while\"",
    "\"#endwhile\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"&&\"",
    "\"||\"",
    "\"$\"",
    "\"@\"",
    "\"random_float\"",
    "\"random_list\"",
    "\"random_int\"",
    "\"prod\"",
    "\"sum\"",
    "\"diff\"",
    "\"quot\"",
    "\"round\"",
    "\"trim\"",
    "\"space\"",
    "\"def\"",
    "\"ndef\"",
    "\"concat\"",
    "\"length\"",
    "\"getitemat\"",
    "\"additemat\"",
    "\"delitemat\"",
    "\"#\"",
    "\"=\"",
    "\",\"",
    "<ID>",
    "<SPECIAL>",
    "<NUM>",
    "\"\\\"\"",
  };

}
