/* Generated By:JavaCC: Do not edit this line. TTaemsGrammarConstants.java */
package taems.parser;

public interface TTaemsGrammarConstants {

  int EOF = 0;
  int COMMENT = 1;
  int LPAREN = 7;
  int RPAREN = 8;
  int SPECAGENT = 9;
  int LABEL = 10;
  int SPECTASKGROUP = 11;
  int AGENT = 12;
  int SUBTASKS = 13;
  int QAF = 14;
  int ARRIVAL = 15;
  int EST = 16;
  int DEADLINE = 17;
  int DELIM = 18;
  int SPECTASK = 19;
  int SUPERTASKS = 20;
  int SPECMETHOD = 21;
  int OUTCOMES = 22;
  int DENSITY = 23;
  int QDIST = 24;
  int DDIST = 25;
  int CDIST = 26;
  int TDIST = 27;
  int RATING = 28;
  int PCPU = 29;
  int START = 30;
  int FINISH = 31;
  int ACCRUED = 32;
  int INTERRELATIONSHIP = 33;
  int SPECENABLES = 34;
  int SPECDISABLES = 35;
  int FROMO = 36;
  int FROM = 37;
  int TO = 38;
  int DELAY = 39;
  int SPECATTRIBUTES = 40;
  int SPECFACILITATES = 41;
  int SPECHINDERS = 42;
  int SPECUSES = 43;
  int SPECLIMITS = 44;
  int SPECPRODUCES = 45;
  int SPECCONSUMES = 46;
  int SPECCRESOURCE = 47;
  int SPECNCRESOURCE = 48;
  int MODEL = 49;
  int DURATIONINDEPENDENT = 50;
  int PERTIMEUNIT = 51;
  int RESOURCE = 52;
  int QUANTITY = 53;
  int STATE = 54;
  int DEPLETEDAT = 55;
  int OVERLOADEDAT = 56;
  int QPOWER = 57;
  int DPOWER = 58;
  int CPOWER = 59;
  int SPECCOMMIT = 60;
  int SPECNLCOMMIT = 61;
  int TYPE = 62;
  int TASK = 63;
  int NEGOTIABILITY = 64;
  int UTIL = 65;
  int IMPORTANCE = 66;
  int MINQ = 67;
  int SAT = 68;
  int FROMAGENT = 69;
  int TOAGENT = 70;
  int SCHEDULES = 71;
  int SPECSCHED = 72;
  int SPECMLCSCHED = 73;
  int SCHEDELEMS = 74;
  int SCHEDELEM = 75;
  int PRECONS = 76;
  int PRECPRE = 77;
  int EARLIESTPRE = 78;
  int STARTDIST = 79;
  int FINISHDIST = 80;
  int QMON = 81;
  int DMON = 82;
  int TASKQINFOS = 83;
  int COMMITINFO = 84;
  int SPECSSB = 85;
  int QVAL = 86;
  int DVAL = 87;
  int CVAL = 88;
  int SPECEVALCRIT = 89;
  int GOODNESSQS = 90;
  int GOODNESSCS = 91;
  int GOODNESSDS = 92;
  int THRESHQS = 93;
  int THRESHCS = 94;
  int THRESHDS = 95;
  int QTHRESH = 96;
  int CLIMIT = 97;
  int DLIMIT = 98;
  int UNCERTAINQS = 99;
  int UNCERTAINCS = 100;
  int UNCERTAINDS = 101;
  int THRESHCERTQS = 102;
  int THRESHCERTDS = 103;
  int THRESHCERTCS = 104;
  int QUALCERTTHRESH = 105;
  int COSTCERTTHRESH = 106;
  int DURCERTTHRESH = 107;
  int METAGS = 108;
  int METATS = 109;
  int METAUS = 110;
  int METAUTS = 111;
  int CONSUMES = 112;
  int PRODUCES = 113;
  int DIS = 114;
  int DIE = 115;
  int NONLOCAL = 116;
  int OLDNONLOCAL = 117;
  int NUM = 118;
  int ID = 119;
  int SPECIAL = 120;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"spec_agent\"",
    "\"label\"",
    "\"spec_task_group\"",
    "\"agent\"",
    "\"subtasks\"",
    "\"qaf\"",
    "\"arrival_time\"",
    "\"earliest_start_time\"",
    "\"deadline\"",
    "\"DELIM\"",
    "\"spec_task\"",
    "\"supertasks\"",
    "\"spec_method\"",
    "\"outcomes\"",
    "\"density\"",
    "\"quality_distribution\"",
    "\"duration_distribution\"",
    "\"cost_distribution\"",
    "\"time_distribution\"",
    "\"rating\"",
    "\"percentage_of_cpu_used\"",
    "\"start_time\"",
    "\"finish_time\"",
    "\"accrued_time\"",
    "\"interrelationship\"",
    "\"spec_enables\"",
    "\"spec_disables\"",
    "\"from_outcome\"",
    "\"from\"",
    "\"to\"",
    "\"delay\"",
    "\"spec_attributes\"",
    "\"spec_facilitates\"",
    "\"spec_hinders\"",
    "\"spec_uses\"",
    "\"spec_limits\"",
    "\"spec_produces\"",
    "\"spec_consumes\"",
    "\"spec_consumable_resource\"",
    "\"spec_non_consumable_resource\"",
    "\"model\"",
    "\"duration_independent\"",
    "\"per_time_unit\"",
    "\"resource\"",
    "\"quantity\"",
    "\"state\"",
    "\"depleted_at\"",
    "\"overloaded_at\"",
    "\"quality_power\"",
    "\"duration_power\"",
    "\"cost_power\"",
    "\"spec_commitment\"",
    "\"spec_nonlocal_commitment\"",
    "\"type\"",
    "\"task\"",
    "\"negotiability\"",
    "\"utility\"",
    "\"importance\"",
    "\"minimum_quality\"",
    "\"time_satisfied\"",
    "\"from_agent\"",
    "\"to_agent\"",
    "\"schedules\"",
    "\"spec_schedule\"",
    "\"spec_mlc_schedule\"",
    "\"schedule_elements\"",
    "\"schedule_element\"",
    "\"preconditions\"",
    "\"spec_precedence_precondition\"",
    "\"spec_earlieststarttime_precondition\"",
    "\"start_time_distribution\"",
    "\"finish_time_distribution\"",
    "\"quality_monitoring_info\"",
    "\"duration_monitoring_info\"",
    "\"task_quality_infos\"",
    "\"commitment_info\"",
    "\"spec_schedule_setting_bundle\"",
    "\"quality_value\"",
    "\"duration_value\"",
    "\"cost_value\"",
    "\"spec_evaluation_criteria\"",
    "\"goodness_quality_slider\"",
    "\"goodness_cost_slider\"",
    "\"goodness_duration_slider\"",
    "\"threshold_quality_slider\"",
    "\"threshold_cost_slider\"",
    "\"threshold_duration_slider\"",
    "\"quality_threshold\"",
    "\"cost_limit\"",
    "\"duration_limit\"",
    "\"uncertainty_quality_slider\"",
    "\"uncertainty_cost_slider\"",
    "\"uncertainty_duration_slider\"",
    "\"threshold_certainty_quality_slider\"",
    "\"threshold_certainty_duration_slider\"",
    "\"threshold_certainty_cost_slider\"",
    "\"quality_certainty_threshold\"",
    "\"cost_certainty_threshold\"",
    "\"duration_certainty_threshold\"",
    "\"meta_goodness_slider\"",
    "\"meta_threshold_slider\"",
    "\"meta_uncertainty_slider\"",
    "\"meta_uncertainty_threshold_slider\"",
    "\"consumes\"",
    "\"produces\"",
    "\"dont_interval_start\"",
    "\"dont_interval_end\"",
    "\"nonlocal\"",
    "\"method_is_non_local\"",
    "<NUM>",
    "<ID>",
    "<SPECIAL>",
  };

}
